### PR TITLE
452 automated testing

### PR DESCRIPTION
**Pull request by abujeda**
Added new automated testing project based on Cypress testing framework.

Created new proposal to pre-build ondemand and slurm images to improve automated tests running time.

### CODE REVIEW

**Comment by abujeda** [comment]
Copying comments from old PR:#33
@whorka wrote:
Build fails:

$ make
...
Pulling slurmdbd (snkattck/slurm-docker-cluster:slurm-21-08-2-1)...
ERROR: manifest for snkattck/slurm-docker-cluster:slurm-21-08-2-1 not found: manifest unknown: manifest unknown
I believe that the slurm-docker-cluster container images have been moved to our official Docker Hub organization: https://hub.docker.com/u/hmdc

**Comment by abujeda** [comment]
> @adaybujeda this PR's branch appears to be in an unofficial forked repo. In the future, please push feature branches to the official repo for PRs.

This is now fixed. Added changes to local branch and created new PR

**Comment by abujeda** [comment]
Fixed the Docker container configuration and added the test to launch RStudio from the OOD dashboard.
This test fails in the local environment (until we fix the current issue), but works in remote-dev.

**Review by whorka — APPROVED** [review]
Looks good to me.

**Review by doprdele — APPROVED** [review]

**Pull request merged**
