### PR TITLE
change make target name to remote-dev to reflect its nature

### PR DESCRIPTION
**Pull request by iqlinuxadmin**
Tiny change so that we will be doing 
make remote-dev
instead of 
make qa
which better reflects our nomenclature.

Addresses [this comment](https://github.com/hmdc/DevOpsProjects/issues/446#issuecomment-880944719) in [#446](https://github.com/hmdc/DevOpsProjects/issues/446)

### CODE REVIEW

**Comment by whorka** [comment]
@iqlinuxadmin What's the issue number for this? I can't find it on the board. Could you please link it from the issue description?

**Comment by whorka** [comment]
~Also, I don't know if it's worth making a separate issue for, so maybe we can tack it on here: the deployment to remote dev should **remove** any pre-existing deployment (`rsync --delete`) so that the deployment is not cluttered with obsolete and potentially confounding files.~

_Edit: nevermind, this was handled in https://github.com/hmdc/sid2/commit/5fcda9f4d145ea042ac7fe56faad355fb6eec104_

**Comment by whorka** [comment]
> @iqlinuxadmin What's the issue number for this? I can't find it on the board. Could you please link it from the issue description?

Aha! I found this was mentioned in:
- [Spike: Team walks through dev/qa/staging process end-end #446](https://github.com/hmdc/DevOpsProjects/issues/446#)

**Comment by whorka** [comment]
We decided today that this is out of scope from[ #446](https://github.com/hmdc/DevOpsProjects/issues/446#) and provides independent value, so it now has a new issue to track it:
 - [Change make target name to remote-dev to reflect its nature #491](https://github.com/hmdc/DevOpsProjects/issues/491)

**Comment by iqlinuxadmin** [comment]
I actually did use the original issue number in the branch name- 446.  Thinking I should rename the branch.  I'll look into doing that.

**Comment by iqlinuxadmin** [comment]
Branch name changed to start with correct issue number.

**Pull request closed without merging**
