### PR TITLE
DevOpsProjects#483: Added skeleton project for Radius SPI

### PR DESCRIPTION
**Pull request by abujeda**
- https://github.com/hmdc/DevOpsProjects/issues/483

### CODE REVIEW

**Comment by whorka** [comment]
All instances of `com.iqss` should instead be `edu.harvard.iq`. We do not control the domain name `iqss.com`.

Per https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html and https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

@adaybujeda thank you for introducing this intentional error so that we can test the Code Review revision process. 🙂

**Comment by adaybujeda** [comment]
I have updated the names of the packages.

**Comment by abujeda** [comment]
I have updated the names of the packages

**Comment by whorka** [comment]
Looks good to me...
```
[root@sso-dev keycloak-radius-spi]# mvn -version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /root/apache-maven-3.8.1
Java version: 1.8.0_292, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1160.31.1.el7.x86_64", arch: "amd64", family: "unix"
[root@sso-dev keycloak-radius-spi]# mvn clean install
...
[INFO] Installing /root/sid2/keycloak-radius-spi/target/keycloak-radius-spi-jar-with-dependencies.jar to /root/.m2/repository/edu/harvard/iq/keycloak/keycloak-radius-spi/1.0/keycloak-radius-spi-1.0-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by abujeda** [comment]
@whorka I have updated with the latest from the Radius SPI prototype + updates to the README with instructions

**Comment by whorka** [comment]
> @whorka I have updated with the latest from the Radius SPI prototype + updates to the README with instructions

@adaybujeda with the latest update, the jar no longer builds on the prototype Keycloak server:

```
[root@sso-dev keycloak-radius-spi]# PATH=/root/apache-maven-3.8.1/bin:$PATH make build
mvn clean install
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.harvard.iq.keycloak:keycloak-radius-spi:jar:1.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 91, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------< edu.harvard.iq.keycloak:keycloak-radius-spi >-------------
[INFO] Building RADIUS Mfa Keycloak 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.tinyradius:tinyradius:jar:1.1.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.515 s
[INFO] Finished at: 2021-07-22T18:02:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project keycloak-radius-spi: Could not resolve dependencies for project edu.harvard.iq.keycloak:keycloak-radius-spi:jar:1.0: Could not find artifact org.tinyradius:tinyradius:jar:1.1.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
make: *** [build] Error 1
```

**Comment by abujeda** [comment]
@whorka I have fixed the issue.

I forgot that the `org.tinyradius:tinyradius:jar` library is not available in the maven central repository and the maven build command will not find it. In my local environment, I added it manually.

I have added the library to the project and created a hook into maven to install it in the local repo before building the SPI jar.

It should be fixed now

**Comment by whorka** [comment]
Thanks for the fix @adaybujeda , we are one step closer...

I was able to build and install the jar, it loads in Keycloak, and I am able to configure it as part of an auth flow.

However, when I try to use it for authentication, it returns "INVALID TOTP" after several seconds. It looks from the log like the connection to the RADIUS server is timing out:

```
2021-07-23 14:39:59,822 INFO  [org.tinyradius.util.RadiusClient] (default task-2) send Access-Request packet: Access-Request, ID 
1
User-Name: whorka
2021-07-23 14:40:02,831 INFO  [org.tinyradius.util.RadiusClient] (default task-2) communication failure, retry 1
2021-07-23 14:40:05,835 INFO  [org.tinyradius.util.RadiusClient] (default task-2) communication failure, retry 2
2021-07-23 14:40:08,838 ERROR [org.tinyradius.util.RadiusClient] (default task-2) communication failure (timeout), no more retrie
s
2021-07-23 14:40:08,839 ERROR [edu.harvard.iq.keycloak.auth.spi.RadiusAuthService] (default task-2) action=radiusAuth result=erro
r host=openauth.rc.fas.harvard.edu:1812 username=whorka: java.net.SocketTimeoutException: Receive timed out
```

I will check with FASRC to see if communications between the prototype Keycloak server and the production RADIUS server are currently permitted or if something needs to be reconfigured.

**Comment by whorka** [comment]
Also @adaybujeda the command you documented for [testing RADIUS connectivity](https://github.com/hmdc/sid2/pull/11/files#diff-d18b50352ae8ce334b7a653a2932a52665a1f667678e4b62fa76cfbc00a3f224R60) fails with a Java error:

```
[root@sso-dev keycloak-radius-spi]# java -cp /root/sid2/keycloak-radius-spi/target/keycloak-radius-spi-jar-with-dependencies.jar edu.harvard.iq.keycloak.auth.spi.RadiusConnectivityCheck sso-dev.rc.fas.harvard.edu '[REDACTED]' whorka 999999
Connecting to: sso-dev.rc.fas.harvard.edu secret: [REDACTED] username: whorka password: 999999
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
	at org.tinyradius.packet.AccessRequest.<clinit>(AccessRequest.java:481)
	at edu.harvard.iq.keycloak.auth.spi.RadiusConnectivityCheck.main(RadiusConnectivityCheck.java:14)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 2 more
```

**Comment by whorka** [comment]
> I will check with FASRC to see if communications between the prototype Keycloak server and the production RADIUS server are currently permitted or if something needs to be reconfigured.

The network path is open, but the RADIUS server has not yet been configured to permit the prototype Keycloak server as a client, so that is why the RADIUS SPI is not able to connect. I will work with FASRC to get this configured.

I can't account for the error from the connectivity test command. It looks like a logging error.

**Comment by abujeda** [comment]
@whorka I have fixed the Radius connectivity utility, I added the missing library by using the original POM from the `tinyradius` project.

I was able to reproduce the issue initially and after the update, the error is gone.

**Comment by whorka** [comment]
After the latest update, I confirmed that `log4j` initializes correctly when running the `edu.harvard.iq.keycloak.auth.spi.RadiusConnectivityCheck` class directly on the command line.

However, the connection to the RADIUS server times out. I will follow up with FASRC again today about granting access.

**Comment by whorka** [comment]
Finally got this working on the prototype Keycloak server @adaybujeda .

It turns out that I had been misinformed about the address of the production RADIUS server. Once I filled in the correct IP address, everything worked, both from the standalone class CLI and the Keycloak SPI.

**Comment by abujeda** [comment]
Already merged by another PR

**Pull request closed without merging**
