### PR TITLE
#598 and #602 - Added custom launchers, quick links, and banner per HPC cluster

### PR DESCRIPTION
**Pull request by abujeda**
Updates to support customizations of quick launchers, quick links, and banner per HPC cluster.

This will allow to have a different set of launchers, links, and banner for Development, Cannon and FASSE.

### CODE REVIEW

**Comment by whorka** [comment]
I noticed that the `dashboard/README` file is out of date while following the setup instructions (it said that the Dashboard is not yet usable), so I committed an update to this branch.

**Review by whorka — CHANGES_REQUESTED** [review]
@adaybujeda I am unable to complete the review on this branch. While following the instructions for Validation of the dev environment as described in `dashboard/README`, it fails on the step "Can you run and connect to RStudio through the original OpenOnDemand dashboard?"

When I try to run RStudio from the default OOD dashboard, it returns a blank page at http://localhost:33000/pun/sys/dashboard/batch_connect/sys/Rstudio/session_contexts after clicking the "Launch" button, and the RStudio job does not start.

Are you able to reproduce this problem as a bug in this branch, or is there possibly something wrong with my local dev environment?

**Comment by whorka** [comment]
> When I try to run RStudio from the default OOD dashboard, it returns a blank page at http://localhost:33000/pun/sys/dashboard/batch_connect/sys/Rstudio/session_contexts after clicking the "Launch" button, and the RStudio job does not start.

@adaybujeda I am getting the same behavior from the `canary` branch also, in both Firefox and Chromium. Is it just me, or can you reproduce this?

**Comment by abujeda** [comment]
@whorka I am getting the same error, the blank page when starting an interactive session from the main dashboard application. Investigating...

**Comment by whorka** [comment]
If I skip this Validation step of launching RStudio from the default OOD dashboard, I am able to initialize the Sid dashboard and successfully launch RStudio from the Sid dashboard, so the underlying SLURM cluster appears to be functioning correctly, both in the `canary` branch and in this `598-custom-launchers-per-cluster` feature branch.

The initialization of the Sid dashboard app does throw an HTTP 502 proxy error (Reason: Error reading from remote server) instead of returning success, however. I think the initialization might be exceeding some configured timeout. This is a separate issue and also occurs for me on both the `canary` branch and this feature branch.

These seem like errors that might have been detected by the automated testing, so I can also try testing [that branch](https://github.com/hmdc/sid2/pull/33) first and if it works better we can merge and rebase from that.

**Comment by abujeda** [comment]
The problem seems to be related with the main Dashboard` Cross Site Request Forgery (CSRF)` protection that is failing, causing the back-end to return an error. This seems to be happening since the upgrade to OOD 2.0.x. In the initial 1.8 version is ok (I tested it with the `google_analytics` branch).

This only affects the local environment.

We can downgrade the local environment back to 1.8 while we investigate. Or we can bypass this validation until we fix it.

PS: The automated tests do not start an RStudio interactive session for the default dashboard. Will add it

**Comment by whorka** [comment]
> The problem seems to be related with the main Dashboard` Cross Site Request Forgery (CSRF)` protection that is failing, causing the back-end to return an error. This seems to be happening since the upgrade to OOD 2.0.x. In the initial 1.8 version is ok (I tested it with the `google_analytics` branch).
> 
> This only affects the local environment.
> 
> We can downgrade the local environment back to 1.8 while we investigate. Or we can bypass this validation until we fix it.

OK, so this should have been detected as part of review of https://github.com/hmdc/DevOpsProjects/issues/487 , but it was not.

If you are confident that this only affects the local environment then I think that it is safe to bypass this validation step for now, but please open a new issue to fix this error.

> PS: The automated tests do not start an RStudio interactive session for the default dashboard. Will add it

Please do, in the PR for automated testing, https://github.com/hmdc/sid2/pull/37

**Comment by abujeda** [comment]
I have tested locally this branch with OOD 1.8.1 and the error when launching interactive apps in the OOD dashboard is not happening. Will continue the investigation to see if I can fix the CSRF error.

Will continue the discussion tomorrow in the daily

**Comment by abujeda** [comment]
I have found the problem with OOD 2.0.x
By default, OOD 2.0.x only supports the creation of session cookies under HTTPS. As we are using HTTP, session cookies are not created and the CSRF token cannot be validated. This failed validation is what is causing the errors when creating an interactive session.

I have committed a fix to override this configuration.

Created a new issue in case we want to upgrade our local environment to use HTTPS:
https://github.com/hmdc/DevOpsProjects/issues/605

**Comment by abujeda** [comment]
Changes from issue https://github.com/hmdc/DevOpsProjects/issues/602 have been merged into this PR

**Review by whorka — CHANGES_REQUESTED** [review]
Almost there @adaybujeda . There's just one thing left to fix and then this PR can pass review.

When I load the dashboard in Remote Development, it fails the validation test in the description of issue https://github.com/hmdc/DevOpsProjects/issues/602:

>  At the top of the page, there should be a banner with the message: Social Sciences dashboard on the Cannon cluster

Instead, the banner reads: "Social Sciences dashboard on the Development cluster"

**Comment by abujeda** [comment]
Sorry @whorka, I missed the banner configuration when moving the changes from the previous PR.

This is fixed now. Ready again.

**Review by whorka — APPROVED** [review]
I think that should do it then @adaybujeda . There was still a small typo but I fixed it.

**Pull request merged**
